# Generated by Django 2.2 on 2020-06-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proce',
            new_name='price',
        ),
    ]
