# Generated by Django 2.2 on 2020-06-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200602_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custumer',
            new_name='customer',
        ),
    ]
