# Generated by Django 2.2 on 2020-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200606_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bo', 'Bolsas'), ('Ci', 'Cintos'), ('Ca', 'Carteiras'), ('Es', 'Escolar'), ('Ar', 'Armarinho'), ('Br', 'Briquedos')], max_length=2),
        ),
    ]
